sonar.projectKey=sistema-legado
sonar.projectName=SistemaLegado
sonar.sources=.
sonar.exclusions=migrations/versions/**,**/__pycache__/**,.sonar/**
sonar.coverage.exclusions=migrations/**,tests/**,**/__pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
