"""add status to demandas

Revision ID: a1558870ac3a
Revises: 20260422_01
Create Date: 2026-05-12 20:26:00.138098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1558870ac3a'
down_revision = '20260422_01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demandas', sa.Column('status', sa.Text(), server_default='Aberto', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demandas', 'status')
    # ### end Alembic commands ###

